### ISSUE TITLE
Missing case in getIntersectPoint

### ISSUE THREAD

**Issue by paulinegarelli** [kth-cdate-courses/DD2480#93]
When the line (p2,p3) is horizontal, we cannot find the equation of the perpendicular line in the same way.

We need to add the case:
`if (k1 == 0) {
x = x1;
y = y2;
}`
p1 and our intersect point have the same x coordinate because the perpendicular line is vertical.
p2, p3 and our intersect point have the same y coordinate because the first line is horizontal.

**Comment by hampfh** [comment]
p2 and p3 on same coordinates
